name: SmartLocker Tests
# GitHub Actions YML
# runs pipe when code is pushed to main and pull request created against main
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
# GitHub to create a temporary Linux machine to ensure app runs on fresh machine
    runs-on: ubuntu-latest

    steps:
# Downloads repository onto the GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest